[config.wallpaper]
command = "bash"
arguments = ["-c", "hyprctl hyprpaper preload {image} && hyprctl hyprpaper wallpaper ,{image}"]
set = true

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors/matugen.css'
post_hook = 'pkill -SIGUSR2 waybar && pkill -SIGUSR2 swaync'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/colors.conf'
post_hook = "kill -SIGUSR1 $(pidof kitty)"

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'


